<<<<<<< HEAD
sudo: required

services:
  - docker
  - postgresql

env:
  - RAILS_ENV=test

install:
  - docker-compose build
  - docker-compose up -d && docker ps

script:
  - docker-compose run web bundle exec rake db:create db:migrate
  - docker-compose run web bundle exec rake
