sudo: required

services:
  - docker

env:
  - RAILS_ENV=test

install:
  - script/yacs-build
  - script/yacs-startd  && docker ps
  - script/yacs-dbsetup
before_script:
  - sleep 10
script:
  - script/yacs-test
