sudo: required

# language: ruby

# rvm:
#   - 2.2.3

services:
  - docker
  - postgresql

env:
  - RAILS_ENV=test

install:
  - docker-compose build

script:
  - docker-compose run web rake db:create db:migrate
  - docker-compose run web rake
