sudo: required

services:
  - docker

env:
  - RAILS_ENV=test

install:
  - docker-compose build

before_script:
  - docker-compose run web rake db:create db:migrate

script:
  - docker-compose run web rake
