sudo: required

language: ruby

rvm:
  - 2.2.3

services:
  - npm
  - postgresql
  - redis

addons:
  hosts:
    - postgres
    - redis

env:
  - RAILS_ENV=test
  - SECRET_KEY_BASE=gyq3dgq378dhqd8qdqudbdq3d
  - SECRET_TOKEN=d2huqdwhq8dq23d8qhd2389

install:
  - npm install -g eslint
  - bundle install
  - sleep 10
  - rake db:create
  - rake db:test:prepare

script:
  - bundle exec rake
  - eslint app/assets/javascripts/ vendor/assets/javascripts/schedule --config config/eslint.json --max-warnings 12
