version: '2'

services:
  postgres:
    image: postgres:9.5
    expose:
      - "5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    expose:
      - "6379"
    volumes:
      - ./data/redis/:/var/lib/redis/data/

  nginx:
    build: nginx
    ports:
      - "80:80"
    links:
      - web
    volumes:
      - .:/usr/src/app/

  web:
    extends:
      file: docker-compose.common.yml
      service: rails
    depends_on:
      - postgres
      - redis
    command: bundle exec puma -C config/puma.rb
    expose:
      - "3000"

  crono:
    extends:
      file: docker-compose.common.yml
      service: rails
    depends_on:
      - postgres
      - redis
    command: bundle exec crono
