version: '3'

services:
  postgres:
    image: postgres:9.5.6
    expose:
      - "5432"

  redis:
    image: redis:4-alpine
    expose:
      - "6379"

  nginx:
    image: yacsrcos/yacs-nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - core
    volumes:
      - ./ssl:/etc/ssl/yacs

  core:
    image: yacsrcos/yacs
    environment:
      - RAILS_ENV
      - SECRET_KEY_BASE
      - SECRET_TOKEN
      - WEB_CONCURRENCY
      - MAX_THREADS
    volumes:
      - ./ssl:/etc/ssl/yacs
    depends_on:
      - postgres
      - redis
    command: bundle exec puma -C config/puma.rb
    expose:
      - "4100"

  worker:
    image: yacsrcos/yacs
    environment:
      - RAILS_ENV
    depends_on:
      - postgres
      - redis
    command: bundle exec crono

  web:
    image: yacsrcos/yacs-web
    depends_on:
      - core
    expose:
      - "4200"

  admin:
    image: yacsrcos/yacs-admin
    depends_on:
      - core
    expose:
      - "4300"

  users:
    image: yacsrcos/yacs-users
    depends_on:
      - postgres
      - redis
    expose:
      - "4400"

  malg:
    images: yacsrcos/yacs-malg
    links:
      - core
    expose:
      - "4500"
