version: '2'

services:
  postgres:
    image: postgres:9.5
    expose:
      - "5432"
    # volumes:
    #   - /Users/rjyoung/data/:/var/lib/postgresql/data/:rw

  redis:
    image: redis
    expose:
      - "6379"
    # volumes:
    #   - ./data/redis/:/var/lib/redis/data/

  nginx:
    build: nginx
    ports:
      - "80:80"
    links:
      - web
    volumes:
      - .:/usr/src/app/

  crono:
    build: .
    environment:
      - RAILS_ENV=production
    command: bundle exec crono
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app/

  web:
    build: .
    environment:
      - RAILS_ENV=production
    command: bundle exec puma -C config/puma.rb
    expose:
      - "3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app/
