version: '3'

services:
  postgres:
    image: postgres:9.5.6
    restart: unless-stopped
    expose:
      - "5432"

  redis:
    image: redis
    restart: unless-stopped
    expose:
      - "6379"

  nginx:
    build: yacsrcos/yacs-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    links:
      - core
    volumes:
      - ./ssl:/etc/ssl/yacs

  core:
    build: yacsrcos/yacs
    restart: unless-stopped
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - SECRET_TOKEN=${SECRET_TOKEN}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY}
      - MAX_THREADS=${MAX_THREADS}
    volumes:
      - ./ssl:/etc/ssl/yacs
    depends_on:
      - postgres
      - redis
    command: bundle exec puma -C config/puma.rb
    expose:
      - "4100"

  worker:
    build: yacsrcos/yacs
    restart: unless-stopped
    environment:
      - RAILS_ENV=${RAILS_ENV}
    depends_on:
      - postgres
      - redis
    command: bundle exec crono

  web:
    build: yacsrcos/yacs-web
    restart: unless-stopped
    depends_on:
      - core
    expose:
      - "4200"

  admin:
    build: yacsrcos/yacs-admin
    restart: unless-stopped
    depends_on: core
    expose:
      - "4300"

  users:
    build: yacsrcos/yacs-users
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    expose:
      - "4400"
