version: '3'

services:
  postgres:
    image: postgres:9.5.6
    expose:
      - "5432"

  redis:
    image: redis
    expose:
      - "6379"

  nginx:
    build: ./develop/yacs-nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - core

  core:
    build: ./develop/yacs
    environment:
      - RAILS_ENV=development
      - SECRET_KEY_BASE=6ae504547712ae4faf35b9d6186322cf
      - SECRET_TOKEN=cc621dab5bb79f81057a7d17c8ceea42
      - WEB_CONCURRENCY=1
      - MAX_THREADS=2
    ports:
      - "4100:4100"
    volumes:
      - ./develop/yacs:/usr/src/app

  worker:
    build: ./develop/yacs
    environment:
      - RAILS_ENV=development
    volumes:
      - ./develop/yacs:/usr/src/app

  web:
    build: ./develop/yacs-web
    ports:
      - "4200:4200"
    volumes:
      - "./develop/yacs-web/src:/usr/src/app/src"

  # admin:
  #   build: ./develop/yacs-admin
  #   ports:
  #     - "4300:4300"

  users:
    build: ./develop/yacs-users
    ports:
      - "4400:4400"
    volumes:
      - "./develop/yacs-users:/usr/src/app"

  malg:
    build: ./develop/yacs-malg
    ports:
      - "4500:4500"
    volumes:
      - "./develop/yacs-malg:/usr/src/app"

  sidekiq:
    build: "./develop/yacs-malg"
    volumes:
      - "./develop/yacs-malg:/usr/src/app"
    links:
      - core
    command: "ash"
