version: '1'

schema:
  types:
    schools:
      identifier: name
      child_type: departments
    departments:
      identifier: code
      child_type: courses
    courses:
      identifier: number
      child_type: sections
    sections:
      identifier: name


sources:
  acalog:
    location: adapter-acalog
    poll: 86400 # 1 day
    root: departments
  banner:
    location: adapter-banner
    poll: 43200 # 12 hours
    root: departments
  banner-seats:
    location: adapter-banner/seats
    poll: 300 # 5 minutes
    root: sections
  yaml-schools:
    location: adapter-yaml
    poll: 2592000 # 30 days
    root: schools
  csv-topics:
    location: adapter-csv
    poll: 43200 # 12 hours
    root: departments
  # admin:
  #   location: admin
  #   poll: 60 # 1 minute
  #   root: schools

priorities:
  default:
    fields:
      # - admin
      - banner
      - acalog
  schools:
    existence: schools-config
  departments:
    existence: schools-config
  courses:
    existence: banner
    fields:
      name:
        # - admin
        - acalog
        - banner
      description:
        - admin
        - acalog
  sections:
    existence: banner
    fields:
      seats:
        # - admin
        - banner-seats
        - banner
      seats_available:
        # - admin
        - banner-seats
        - banner