version: '3.2'

services:
  malg:
    links:
      - adapter-albert
      - adapter-yaml
    volumes:
      - ./pipelines/nyu/config/sources.yml:/usr/src/app/config/sources.yml

  adapter-albert:
    build: ./pipelines/nyu/adapters/albert
    expose:
      - "4600"
    ports:
      - "4601:4600"
    volumes:
      - ./pipelines/nyu/adapters/albert:/usr/src/app
    tty: true
    stdin_open: true

  adapter-yaml:
    build: ./pipelines/rpi/adapters/yaml-rpi
    expose:
      - "4600"
    ports:
      - "4603:4600"
    volumes:
      - ./pipelines/nyu/adapters/yaml:/usr/src/app
    environment:
      - YAML_SOURCE="schools.yml"
